export const MAX_FOOD_THRESHOLD = 5000;
export const MAX_WATER_THRESHOLD = 5000;
export const MAX_TEMP_THRESHOLD = 50;
export const MAX_HUMIDITY_THRESHOLD = 100;
export const FOOD_WARNING_THRESHOLD = 500;
export const URL_HEADER = "http://localhost:3000";
export const HOME_DATA_URL = "/api/homeData/";
export const IMAGE_URL = "/api/image/";
export const VIDEO_URL = "/api/video/";
export const FEED_HISTORY_URL = "/api/food/";
export const WATER_HISTORY_URL = "/api/water/";
export const ENVIRONMENT_HISTORY_URL = "/api/environment/";
export const FEED_SCHEDULE_URL = "/api/schedule/";
export const LOG_URL = "/api/log/";
export const CAMERA_URL = "/api/camera/";
export const DEVICE_URL = "/api/status/";
export const FEED_NOW_URL = "/api/feedNow/";
export const RESTART_URL = "/api/restart/";

export const WATER_WARNING_THRESHOLD = 500;
export const TEMPERATURE_WARNING_THRESHOLD = 30;
export const HUMIDITY_WARNING_THRESHOLD = 200;
export const TIME_FETCH_INTERVAL = 300000; // 5 minutes
